container:
  image: archlinux:base-devel
  cpu: 2
  memory: 2G

busybox_task:
  preparation_script:
    - pacman -Suy --noconfirm base-devel emscripten kernel-headers-musl cmake wget git
    - ln -sf /usr/lib/emscripten/emcc /usr/lib/emscripten/emgcc
    - ln -sf /usr/lib/emscripten/emcc.py /usr/lib/emscripten/emgcc.py
    - ln -sf /usr/bin/core_perl/pod2* /usr/bin/
    - wget https://www.busybox.net/downloads/busybox-1.36.1.tar.bz2
    - tar xjf busybox-1.36.1.tar.bz2
    - cp config busybox-1.36.1/.config
  build_script:
    - source /etc/profile.d/emscripten.sh
    - cd busybox-1.36.1
    - emmake make CC=musl-gcc CFLAGS="-o busybox.wasm"
#    - emcc *.c -o hello.wasm
    - tar cf ../busybox-1.36.1.tar ./*
  wasm_artifacts:
    path: "busybox-1.36.1.tar"
    
