container:
  image: debian:stable-slim
  cpu: 4
  memory: 8G
env:
  LFS: /tmp/cirrus-ci-build/lfs

build_task:
  preparation_script:
    - apt update -y
    - apt upgrade -y
    - apt install -y bison git docbook-xml docbook-xsl g++ xsltproc
        gawk gcc m4 make patch perl python-is-python3 libxml2-utils
        texinfo xz-utils wget sudo libxml2 libxslt1.1 docbook docbook-xsl-ns
    - adduser lfs --disabled-password
    - echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    - mkdir -pv $LFS/{sources,etc,var,lib64,tools} $LFS/usr/{bin,lib,sbin}
    - ln -sv $LFS/usr/bin $LFS/bin
    - ln -sv $LFS/usr/sbin $LFS/sbin
    - ln -sv $LFS/usr/lib $LFS/lib
    - chown -v lfs $LFS/{usr{,/*},lib,lib64,var,etc,bin,sbin,tools}
    - chmod -v a+wt $LFS/sources
    - su - lfs
    - echo "exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash" >> ~/.bash_profile
    - echo -e "
        set +h \n
        umask 022 \n
        LFS=/tmp/cirrus-ci-build/lfs \n
        LC_ALL=POSIX \n
        LFS_TGT=$(uname -m)-lfs-linux-gnu \n
        PATH=/usr/bin \n
        if [ ! -L /bin ]; then PATH=/bin:$PATH; fi \n
        PATH=$LFS/tools/bin:$PATH \n
        CONFIG_SITE=$LFS/usr/share/config.site \n
        export LFS LC_ALL LFS_TGT PATH CONFIG_SITE \n" >> ~/.bashrc
    - git clone https://git.linuxfromscratch.org/jhalfs.git
    - cp -rf configuration jhalfs/
  cross_compiler_script:
    - su - lfs
    - cd $LFS/../jhalfs
    - sed -i 's/read -r ANSWER/ANSWER="yes"/g' jhalfs
    - sed -i 's/read ANSWER/ANSWER="yes"/g' optimize/optimize_functions
    - ./jhalfs run
    - sed -i 's/exit/#/g' $LFS/jhalfs/Makefile
    - make -C $LFS/jhalfs
    - ls
    - tar -cf ../jhalfs.tar ../jhalfs
    - tar -cf ../lfs.tar ../lfs
  jhalfs_artifacts:
    path: "jhalfs.tar"
  lfs_artifacts:
    path: "lfs.tar"
