container:
  image: debian:stable-slim
  cpu: 1
  memory: 1G
env:
  LFS: /mnt/lfs
  MAKEFLAGS: '-j1'

build_task:
  preparation_script:
    - apt update -y
    - apt upgrade -y
    - apt install -y bash binutils bison coreutils diffutils findutils git docbook-xml
        gawk gcc grep gzip m4 make patch perl python-is-python3 sed tar libxml2-utils
        texinfo xz-utils wget sudo libxml2 libxslt1.1 docbook docbook-xsl-ns xsltproc
    - adduser lfs --disabled-password
    - echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    - mkdir -pv $LFS/{sources,etc,var,lib64,tools} $LFS/usr/{bin,lib,sbin}
    - ln -sv $LFS/usr/bin $LFS/bin
    - ln -sv $LFS/usr/sbin $LFS/sbin
    - ln -sv $LFS/usr/lib $LFS/lib
    - chown -v lfs $LFS/{usr{,/*},lib,lib64,var,etc,bin,sbin,tools}
    - chmod -v a+wt $LFS/sources
    - su - lfs
    - echo "exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash" >> ~/.bash_profile
    - echo -e "
        set +h \n
        umask 022 \n
        LFS=/mnt/lfs \n
        LC_ALL=POSIX \n
        LFS_TGT=$(uname -m)-lfs-linux-gnu \n
        PATH=/usr/bin \n
        if [ ! -L /bin ]; then PATH=/bin:$PATH; fi \n
        PATH=$LFS/tools/bin:$PATH \n
        CONFIG_SITE=$LFS/usr/share/config.site \n
        export LFS LC_ALL LFS_TGT PATH CONFIG_SITE \n"
    - git clone https://git.linuxfromscratch.org/jhalfs.git /mnt/jhalfs
    - cp -rf configuration /mnt/jhalfs/
  cross_compiler_script:
    - su - lfs
    - cd /mnt/jhalfs
    - sed -i '134,140d' jhalfs
    - ./jhalfs run
    - cd ../
    - tar -cf jhalfs
  lfs_commands_artifacts:
    path: "/mnt/jhalfs.tar"
