container:
  image: archlinux
  cpu: 1
  memory: 1G

build_task:
  preparation_script:
    - chmod -R 777 ./
    - pacman -Suyy --noconfirm git archiso sudo
    - wget https://mirror.cachyos.org/cachyos-repo.tar.xz
    - tar xvf cachyos-repo.tar.xz 
    - cd cachyos-repo
    - sudo ./cachyos-repo.sh
    - useradd user
    - echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    - cd ../PKGBUILD
    - cat /etc/makepkg.conf
    - echo 'PKGDEST="/repo/"' >> /etc/makepkg.conf
    - su user -
    - for i in ./*; do
        makepkg -si
      done
    - repo-add /repo/pkgs.db.tar.gz /repo/*.pkg.tar.zst
    - cp -r /usr/share/archiso/configs/baseline/ ./
    - cp -f {packages.x86_64,pacman.conf} baseline/
    - mkarchiso -v ../baseline/profiledef.sh
  jhalfs_artifacts:
    path: "work/*"
