container:
  image: archlinux:base-devel
  cpu: 2
  memory: 2G

build_task:
  preparation_script:
    - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    - locale-gen
    - pacman-key --init
    - pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com
    - pacman-key --lsign-key F3B607488DB35A47
    - pacman -Suy --noconfirm wget git sudo base-devel archiso
    - pacman -U --noconfirm 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-keyring-3-1-any.pkg.tar.zst' 
        'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-mirrorlist-18-1-any.pkg.tar.zst' 
        'https://mirror.cachyos.org/repo/x86_64/cachyos/pacman-6.0.2-14-x86_64.pkg.tar.zst'
    - mkdir /repo
    - useradd user
    - echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  package_build_script:
    - cd PKGBUILDs
    - git clone https://aur.archlinux.org/thorium-browser-bin.git
    - git clone https://aur.archlinux.org/dinit.git
    - git clone https://aur.archlinux.org/dwl.git
    - wget https://www.skarnet.org/software/skalibs/skalibs-2.13.1.1.tar.gz
    - tar xvzf skalibs-2.13.1.1.tar.gz
    - cd skalibs-2.13.1.1
    - ./configure --prefix=/usr --datadir=/etc
    - make
    - make install
#    - cd skalibs # not work
#    - su user -c "makepkg -si --noconfirm"
    - for i in ../*; do
        cd "$i"; su user -c "makepkg -s --noconfirm";
        cp *.pkg.tar.zst /repo/;
      done
    - repo-add /repo/pkgs.db.tar.gz /repo/*.pkg.tar.zst
    - cp -f ../pacman.conf /etc/
    - pacman -Sy
  distribution_build_script:
    - cp -r /usr/share/archiso/configs/baseline/ ./
    - cp -f {packages.x86_64,pacman.conf} ./baseline/
    - ls ./baseline/
    - mkarchiso -v ./baseline/profiledef.sh
    - ls work/
  jhalfs_artifacts:
    path: "work/*"
