container:
  image: archlinux:base-devel
  cpu: 2
  memory: 2G

busybox_task:
  preparation_script:
    - pacman -Suy --noconfirm base-devel emscripten cmake wget git
    - wget https://www.busybox.net/downloads/busybox-1.36.1.tar.bz2
    - tar xjf busybox-1.36.1.tar.bz2
  build_script:
    - cd busybox-1.36.1
    - emmake make
#    - emcc *.c -o hello.wasm
  wasm_artifacts:
    path: "busybox-1.36.1/busybox.wasm"
    
