container:
  image: archlinux:base-devel
  cpu: 2
  memory: 2G
env:
  LANG: "C"

busybox_task:
  preparation_script:
    - pacman -Suy --noconfirm base-devel emscripten clang linux-api-headers cmake wget git
    - ln -sf /usr/lib/emscripten/emcc /usr/lib/emscripten/emgcc
    - ln -sf /usr/lib/emscripten/emcc.py /usr/lib/emscripten/emgcc.py
    - ln -sf /usr/bin/core_perl/pod2* /usr/bin/
    - clang -v
    - emcc -v
    - wget https://www.busybox.net/downloads/busybox-1.36.1.tar.bz2
    - tar xjf busybox-1.36.1.tar.bz2
    - cd busybox-1.36.1
    - cp ../config .config
    - ln -sf /usr/include/linux ./console-tools/
    - sed -i 's@<linux/kd.h>@"linux/kd.h"@g' console-tools/kbd_mode.c
    - sed -i 's@<linux/types.h>@"linux/types.h"@g' console-tools/linux/kd.h
  build_script:
    - source /etc/profile.d/emscripten.sh
    - cd busybox-1.36.1
    - emmake make SKIP_STRIP=y # CC=emcc SKIP_STRIP=y CFLAGS="-o busybox.wasm" # -I "/usr/lib/modules/6.5.9-arch2-1/build/include/uapi/" # 
#    - emcc *.c -o hello.wasm
    - tar cf ../busybox-1.36.1.tar ./*
  wasm_artifacts:
    path: "busybox-1.36.1.tar"
    
