container:
  image: archlinux:base-devel
  cpu: 1
  memory: 1G

busybox_task:
  preparation_script:
    - pacman -Suy --noconfirm base-devel emscripten cmake wget git
    - ln -sf /usr/lib/emscripten/emcc /usr/lib/emscripten/emgcc
    - wget https://www.busybox.net/downloads/busybox-1.36.1.tar.bz2
    - tar xjf busybox-1.36.1.tar.bz2
    - cp config busybox-1.36.1/.config
  build_script:
    - source /etc/profile.d/emscripten.sh
    - cd busybox-1.36.1
    - emmake make
#    - emcc *.c -o hello.wasm
  wasm_artifacts:
    path: "busybox-1.36.1/busybox.wasm"
    
